version: "3"
#NETWORK
networks: 
  my-network:
    driver: bridge
services: 
  my-database-service:
    container_name: 'my-database'
    build: 
      context: ./
      dockerfile: Dockerfile
    image: 'mongo'
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=dev
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
      - ./storages/dev/data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - my-network