@startuml Application use cases diagram
skinparam actorStyle awesome
title UML of users


class Customer{
    --property--
    name: string 
    address: string
    *password: string 
    *email: string 
    phoneNumber: string 
    gender: string 
    cart: string
    transaction: Array
    billing: Array
    createdAt: Date
    updatedAt: Date
    roles: array
}

class Agency{
    --property--
    name: string 
    address: string 
    email: string 
    *password: string
    *phoneNumber: string 
    gender: string 
    product: object
    transaction: Array
    billing: Array
    createdAt: Date
    updatedAt: Date
    roles: array
}


class Admin{
    --method--
    readAgency(): void 
    createAgency(): void 
    updateAgency(): void
    deleteAgency(): void
}
Admin "1" --* "many" Agency: manage Agency
Customer "many" --* "1" Agency: buy
Agency "many" --* "1" Customer: sell
Admin "belong to" ||--|| Customer



@enduml